# Api Entry Point
api_entrypoint:
    path:     /
    controller: App\Controller\EntryPointController

# Utilisateurs Endpoints
Utilisateurs:
    resource: ./actions/utilisateurs.yaml
    name_prefix: api_
    prefix: api/v1/utilisateurs